# Generated by Django 2.0.dev20170916190531 on 2017-09-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litness', models.IntegerField(default=3)),
                ('safety', models.IntegerField(default=3)),
                ('population', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('num_recommendations', models.IntegerField(default=0)),
                ('radius', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.CharField(max_length=200)),
                ('party_at', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parties.Party')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Song'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parties.Party'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parties.User'),
        ),
    ]
