# Generated by Django 2.0.dev20170916190531 on 2017-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organization',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='cookies',
            field=models.CharField(default='', max_length=200),
        ),
    ]
